# Generated by Django 5.2.4 on 2025-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_university_rep',
            field=models.BooleanField(default=False),
        ),
    ]
