# Generated by Django 5.2.4 on 2025-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='equality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='inclusivity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='living_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='safety_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='support_score',
            field=models.FloatField(default=0.0),
        ),
    ]
