# Generated by Django 5.2.4 on 2025-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='post_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
