# Generated by Django 5.2.4 on 2025-08-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_university_num_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
